-- ─────────────────────────────────────────────────────────────────────────────
-- Training plan storage cleanup (2026-04-15)
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Historical context. Three plan-related tables existed in Supabase:
--
--   training_plans      — declared in supabase-schema.sql, never actually
--                         written to by the app. The `DB.trainingPlans`
--                         accessor in js/db.js was dead code. Removed in
--                         this cleanup commit. The table itself is left
--                         in place as a tombstone — it has no rows and
--                         dropping it would require a schema migration
--                         in every deployed Supabase project. Safe to
--                         drop manually later.
--
--   training_sessions   — used to store per-day scheduled sessions,
--                         mirrored from localStorage.workoutSchedule
--                         via _debouncedSync in js/db.js. The schema
--                         declared `plan_id uuid REFERENCES
--                         training_plans(id) NOT NULL`, but
--                         _shapeTrainingSession has always written
--                         `plan_id: null`. Inserts were working in
--                         production, implying NOT NULL was dropped by
--                         hand in the Supabase SQL Editor without a
--                         migration file. This migration formalizes
--                         that drop, and retargets the FK to the
--                         actual plan store (generated_plans) so
--                         future writes that stamp plan_id won't be
--                         rejected by the wrong FK.
--
--   generated_plans     — the REAL active-plan store. Defined in
--                         supabase-migration-002-fix.sql. Written by
--                         philosophy-planner.js storeGeneratedPlan.
--                         Schema: plan_data jsonb + philosophy module
--                         ids + generation_source + is_active. Untouched
--                         by this migration.
--
-- See docs/TRAINING_PLAN_STORAGE.md for the full model.
-- ─────────────────────────────────────────────────────────────────────────────

-- Step 1: Make plan_id nullable (no-op if already nullable).
ALTER TABLE training_sessions
  ALTER COLUMN plan_id DROP NOT NULL;

-- Step 2: Drop whatever FK constraint currently targets training_plans so
-- we can recreate it pointing at generated_plans. The constraint name
-- is environment-dependent (autogenerated by Postgres), so we discover
-- it via pg_constraint inside a DO block.
DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT conname
      FROM pg_constraint
     WHERE conrelid = 'public.training_sessions'::regclass
       AND contype  = 'f'
       AND pg_get_constraintdef(oid) ILIKE '%plan_id%'
  LOOP
    EXECUTE format('ALTER TABLE training_sessions DROP CONSTRAINT IF EXISTS %I', c.conname);
    RAISE NOTICE 'Dropped FK on training_sessions.plan_id: %', c.conname;
  END LOOP;
END $$;

-- Step 3: Recreate the FK against the real plan store. ON DELETE SET NULL
-- so deleting an active plan doesn't cascade-delete a user's session
-- history — we want those rows to survive as a record of what happened.
ALTER TABLE training_sessions
  ADD CONSTRAINT training_sessions_plan_id_fkey
  FOREIGN KEY (plan_id) REFERENCES generated_plans(id)
  ON DELETE SET NULL;

-- Verify (run after applying):
--   SELECT conname, pg_get_constraintdef(oid)
--     FROM pg_constraint
--    WHERE conrelid = 'public.training_sessions'::regclass
--      AND contype = 'f';
-- Expected: training_sessions_plan_id_fkey references generated_plans(id).
