-- 2026-04-18 — Core tables that were created ad hoc in production but never
-- committed as DDL. Without these CREATE statements a fresh database cannot be
-- stood up: later migrations ALTER/attach policies to them and fail with
-- "relation does not exist", and the app's push/analytics/reminders/admin-Q&A
-- features break silently.
-- ============================================================================
-- Ordering: this file is dated to sort BEFORE the migrations that reference
-- these tables — 20260419c (ask_ironz_logs), 20260503b (notification_prefs
-- ALTER), admin-analytics-migration.sql (analytics_events policies). On a fresh
-- database, run migrations in filename order and this runs first. It is fully
-- idempotent (CREATE TABLE IF NOT EXISTS, DROP POLICY IF EXISTS + CREATE), so
-- running it against the existing production database — where these tables
-- already exist — is a safe no-op that just re-asserts the owner policies.
--
-- Columns mirror the fields the client (js/push.js, js/analytics.js,
-- js/nl-input.js, js/admin-questions.js) and edge functions actually read and
-- write. Admin SELECT/UPDATE policies are intentionally NOT defined here —
-- they are added by their own later migrations (admin-analytics-migration.sql,
-- 20260419c). This file only creates the tables + owner-scoped policies.
-- Edge functions use the service-role key and bypass RLS.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────
-- push_tokens — device push registration (js/push.js; send-push + reminders)
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.push_tokens (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token        text NOT NULL,
  platform     text,
  last_used_at timestamptz DEFAULT now(),
  created_at   timestamptz DEFAULT now(),
  UNIQUE (user_id, token)
);
ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own push tokens" ON public.push_tokens;
CREATE POLICY "Users manage own push tokens" ON public.push_tokens
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────────────────
-- notification_preferences — per-user push settings (js/push.js; reminders)
-- workout_reminder_time is (re)added by 20260503b via ADD COLUMN IF NOT EXISTS;
-- including it here makes that later ALTER a no-op on a fresh DB.
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id                  uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_reminders        boolean DEFAULT true,
  workout_reminder_time    time    DEFAULT '07:00',
  share_alerts             boolean DEFAULT true,
  hydration_reminders      boolean DEFAULT false,
  hydration_start_hour     integer DEFAULT 8,
  hydration_end_hour       integer DEFAULT 20,
  hydration_interval_hours integer DEFAULT 2,
  reminder_minutes_before  integer DEFAULT 30,  -- legacy; retained, ignored by current UI
  updated_at               timestamptz DEFAULT now()
);
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own notification prefs" ON public.notification_preferences;
CREATE POLICY "Users manage own notification prefs" ON public.notification_preferences
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────────────────
-- analytics_events — client analytics (js/analytics.js, error-reporting.js).
-- The owner INSERT policy below is the one admin-analytics-migration.sql
-- refers to as the pre-existing "Users can insert own events" policy; the
-- SELECT (own + admin) policies are added by that migration.
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  event_name text NOT NULL,
  properties jsonb DEFAULT '{}'::jsonb,
  session_id text,
  platform   text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own events" ON public.analytics_events;
CREATE POLICY "Users can insert own events" ON public.analytics_events
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────────────────
-- ask_ironz_logs — Ask-IronZ Q&A log (js/nl-input.js write; admin read).
-- Admin read/update/delete policies are added by 20260419c.
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ask_ironz_logs (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  question_text    text,
  category         text,
  response_type    text,
  tokens_used      integer,
  response_time_ms integer,
  helpful          boolean,
  created_at       timestamptz DEFAULT now()
);
ALTER TABLE public.ask_ironz_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users insert own questions" ON public.ask_ironz_logs;
CREATE POLICY "Users insert own questions" ON public.ask_ironz_logs
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users read own questions" ON public.ask_ironz_logs;
CREATE POLICY "Users read own questions" ON public.ask_ironz_logs
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users update own questions" ON public.ask_ironz_logs;
CREATE POLICY "Users update own questions" ON public.ask_ironz_logs
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────────────────
-- sent_notifications — dedupe ledger for reminder cron functions
-- (check-hydration-reminders, check-workout-reminders). Written only by
-- edge functions via the service-role key, so RLS is enabled with no
-- client-facing policy (service role bypasses RLS).
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sent_notifications (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  notification_type text,
  reference_id      text,
  title             text,
  body              text,
  created_at        timestamptz DEFAULT now()
);
ALTER TABLE public.sent_notifications ENABLE ROW LEVEL SECURITY;
